[[multichain]]
chainID = 421614
name = "Arbitrum Sepolia"
gateway = ""
blkinterval = 1
blkdelay = 5
maxblkdelta = 5000
rfq = ""
[multichain.native]
symbol = "ETH"
address = ""
decimals = 18

[[multichain]]
chainID = 97
name = "BSC Testnet"
gateway = ""
blkinterval = 3
blkdelay = 8
maxblkdelta = 5000
addgasgwei = 2
addgasestimateratio = 0.3
rfq = ""
[multichain.native]
symbol = "BNB"
address = ""
decimals = 18
